export const allCountries = [
    {"label": "Afghanistan", "value": "afghanistan", "code": "AF", "phoneCode": "+93"},
    {"label": "Albania", "value": "albania", "code": "AL", "phoneCode": "+355"},
    {"label": "Algeria", "value": "algeria", "code": "DZ", "phoneCode": "+213"},
    {"label": "Andorra", "value": "andorra", "code": "AD", "phoneCode": "+376"},
    {"label": "Angola", "value": "angola", "code": "AO", "phoneCode": "+244"},
    {"label": "Antigua and Barbuda", "value": "antigua_and_barbuda", "code": "AG", "phoneCode": "+1"},
    {"label": "Argentina", "value": "argentina", "code": "AR", "phoneCode": "+54"},
    {"label": "Armenia", "value": "armenia", "code": "AM", "phoneCode": "+374"},
    {"label": "Australia", "value": "australia", "code": "AU", "phoneCode": "+61"},
    {"label": "Austria", "value": "austria", "code": "AT", "phoneCode": "+43"},
    {"label": "Azerbaijan", "value": "azerbaijan", "code": "AZ", "phoneCode": "+994"},
    {"label": "Bahamas", "value": "bahamas", "code": "BS", "phoneCode": "+1"},
    {"label": "Bahrain", "value": "bahrain", "code": "BH", "phoneCode": "+973"},
    {"label": "Bangladesh", "value": "bangladesh", "code": "BD", "phoneCode": "+880"},
    {"label": "Barbados", "value": "barbados", "code": "BB", "phoneCode": "+1"},
    {"label": "Belarus", "value": "belarus", "code": "BY", "phoneCode": "+375"},
    {"label": "Belgium", "value": "belgium", "code": "BE", "phoneCode": "+32"},
    {"label": "Belize", "value": "belize", "code": "BZ", "phoneCode": "+501"},
    {"label": "Benin", "value": "benin", "code": "BJ", "phoneCode": "+229"},
    {"label": "Bermuda", "value": "bermuda", "code": "BM", "phoneCode": "+1"},
    {"label": "Bhutan", "value": "bhutan", "code": "BT", "phoneCode": "+975"},
    {"label": "Bolivia", "value": "bolivia", "code": "BO", "phoneCode": "+591"},
    {"label": "Bosnia and Herzegovina", "value": "bosnia_and_herzegovina", "code": "BA", "phoneCode": "+387"},
    {"label": "Botswana", "value": "botswana", "code": "BW", "phoneCode": "+267"},
    {"label": "Brazil", "value": "brazil", "code": "BR", "phoneCode": "+55"},
    {"label": "Brunei", "value": "brunei", "code": "BN", "phoneCode": "+673"},
    {"label": "Bulgaria", "value": "bulgaria", "code": "BG", "phoneCode": "+359"},
    {"label": "Burkina Faso", "value": "burkina_faso", "code": "BF", "phoneCode": "+226"},
    {"label": "Burundi", "value": "burundi", "code": "BI", "phoneCode": "+257"},
    {"label": "Cabo Verde", "value": "cabo_verde", "code": "CV", "phoneCode": "+238"},
    {"label": "Cambodia", "value": "cambodia", "code": "KH", "phoneCode": "+855"},
    {"label": "Cameroon", "value": "cameroon", "code": "CM", "phoneCode": "+237"},
    {"label": "Canada", "value": "canada", "code": "CA", "phoneCode": "+1"},
    {"label": "Cayman Islands", "value": "cayman_islands", "code": "KY", "phoneCode": "+1"},
    {"label": "Central African Republic", "value": "central_african_republic", "code": "CF", "phoneCode": "+236"},
    {"label": "Chad", "value": "chad", "code": "TD", "phoneCode": "+235"},
    {"label": "Chile", "value": "chile", "code": "CL", "phoneCode": "+56"},
    {"label": "China", "value": "china", "code": "CN", "phoneCode": "+86"},
    {"label": "Colombia", "value": "colombia", "code": "CO", "phoneCode": "+57"},
    {"label": "Comoros", "value": "comoros", "code": "KM", "phoneCode": "+269"},
    {"label": "Congo", "value": "congo", "code": "CG", "phoneCode": "+242"},
    {"label": "Costa Rica", "value": "costa_rica", "code": "CR", "phoneCode": "+506"},
    {"label": "Croatia", "value": "croatia", "code": "HR", "phoneCode": "+385"},
    {"label": "Cuba", "value": "cuba", "code": "CU", "phoneCode": "+53"},
    {"label": "Cyprus", "value": "cyprus", "code": "CY", "phoneCode": "+357"},
    {"label": "Czech Republic", "value": "czech_republic", "code": "CZ", "phoneCode": "+420"},
    {"label": "Denmark", "value": "denmark", "code": "DK", "phoneCode": "+45"},
    {"label": "Djibouti", "value": "djibouti", "code": "DJ", "phoneCode": "+253"},
    {"label": "Dominica", "value": "dominica", "code": "DM", "phoneCode": "+1"},
    {"label": "Dominican Republic", "value": "dominican_republic", "code": "DO", "phoneCode": "+1"},
    {"label": "Ecuador", "value": "ecuador", "code": "EC", "phoneCode": "+593"},
    {"label": "Egypt", "value": "egypt", "code": "EG", "phoneCode": "+20"},
    {"label": "El Salvador", "value": "el_salvador", "code": "SV", "phoneCode": "+503"},
    {"label": "Equatorial Guinea", "value": "equatorial_guinea", "code": "GQ", "phoneCode": "+240"},
    {"label": "Eritrea", "value": "eritrea", "code": "ER", "phoneCode": "+291"},
    {"label": "Estonia", "value": "estonia", "code": "EE", "phoneCode": "+372"},
    {"label": "Ethiopia", "value": "ethiopia", "code": "ET", "phoneCode": "+251"},
    {"label": "Fiji", "value": "fiji", "code": "FJ", "phoneCode": "+679"},
    {"label": "Finland", "value": "finland", "code": "FI", "phoneCode": "+358"},
    {"label": "France", "value": "france", "code": "FR", "phoneCode": "+33"},
    {"label": "Gabon", "value": "gabon", "code": "GA", "phoneCode": "+241"},
    {"label": "Gambia", "value": "gambia", "code": "GM", "phoneCode": "+220"},
    {"label": "Georgia", "value": "georgia", "code": "GE", "phoneCode": "+995"},
    {"label": "Germany", "value": "germany", "code": "DE", "phoneCode": "+49"},
    {"label": "Ghana", "value": "ghana", "code": "GH", "phoneCode": "+233"},
    {"label": "Greece", "value": "greece", "code": "GR", "phoneCode": "+30"},
    {"label": "Grenada", "value": "grenada", "code": "GD", "phoneCode": "+1"},
    {"label": "Guatemala", "value": "guatemala", "code": "GT", "phoneCode": "+502"},
    {"label": "Guinea", "value": "guinea", "code": "GN", "phoneCode": "+224"},
    {"label": "Guinea-Bissau", "value": "guinea_bissau", "code": "GW", "phoneCode": "+245"},
    {"label": "Guyana", "value": "guyana", "code": "GY", "phoneCode": "+592"},
    {"label": "Haiti", "value": "haiti", "code": "HT", "phoneCode": "+509"},
    {"label": "Honduras", "value": "honduras", "code": "HN", "phoneCode": "+504"},
    {"label": "Hong Kong", "value": "hong_kong", "code": "HK", "phoneCode": "+852"},
    {"label": "Hungary", "value": "hungary", "code": "HU", "phoneCode": "+36"},
    {"label": "Iceland", "value": "iceland", "code": "IS", "phoneCode": "+354"},
    {"label": "India", "value": "india", "code": "IN", "phoneCode": "+91"},
    {"label": "Indonesia", "value": "indonesia", "code": "ID", "phoneCode": "+62"},
    {"label": "Iran", "value": "iran", "code": "IR", "phoneCode": "+98"},
    {"label": "Iraq", "value": "iraq", "code": "IQ", "phoneCode": "+964"},
    {"label": "Ireland", "value": "ireland", "code": "IE", "phoneCode": "+353"},
    {"label": "Israel", "value": "israel", "code": "IL", "phoneCode": "+972"},
    {"label": "Italy", "value": "italy", "code": "IT", "phoneCode": "+39"},
    {"label": "Jamaica", "value": "jamaica", "code": "JM", "phoneCode": "+1"},
    {"label": "Japan", "value": "japan", "code": "JP", "phoneCode": "+81"},
    {"label": "Jordan", "value": "jordan", "code": "JO", "phoneCode": "+962"},
    {"label": "Kazakhstan", "value": "kazakhstan", "code": "KZ", "phoneCode": "+7"},
    {"label": "Kenya", "value": "kenya", "code": "KE", "phoneCode": "+254"},
    {"label": "Kiribati", "value": "kiribati", "code": "KI", "phoneCode": "+686"},
    {"label": "Kuwait", "value": "kuwait", "code": "KW", "phoneCode": "+965"},
    {"label": "Kyrgyzstan", "value": "kyrgyzstan", "code": "KG", "phoneCode": "+996"},
    {"label": "Laos", "value": "laos", "code": "LA", "phoneCode": "+856"},
    {"label": "Latvia", "value": "latvia", "code": "LV", "phoneCode": "+371"},
    {"label": "Lebanon", "value": "lebanon", "code": "LB", "phoneCode": "+961"},
    {"label": "Lesotho", "value": "lesotho", "code": "LS", "phoneCode": "+266"},
    {"label": "Liberia", "value": "liberia", "code": "LR", "phoneCode": "+231"},
    {"label": "Libya", "value": "libya", "code": "LY", "phoneCode": "+218"},
    {"label": "Liechtenstein", "value": "liechtenstein", "code": "LI", "phoneCode": "+423"},
    {"label": "Lithuania", "value": "lithuania", "code": "LT", "phoneCode": "+370"},
    {"label": "Luxembourg", "value": "luxembourg", "code": "LU", "phoneCode": "+352"},
    {"label": "Macao", "value": "macao", "code": "MO", "phoneCode": "+853"},
    {"label": "Macedonia", "value": "macedonia", "code": "MK", "phoneCode": "+389"},
    {"label": "Madagascar", "value": "madagascar", "code": "MG", "phoneCode": "+261"},
    {"label": "Malawi", "value": "malawi", "code": "MW", "phoneCode": "+265"},
    {"label": "Malaysia", "value": "malaysia", "code": "MY", "phoneCode": "+60"},
    {"label": "Maldives", "value": "maldives", "code": "MV", "phoneCode": "+960"},
    {"label": "Mali", "value": "mali", "code": "ML", "phoneCode": "+223"},
    {"label": "Malta", "value": "malta", "code": "MT", "phoneCode": "+356"},
    {"label": "Marshall Islands", "value": "marshall_islands", "code": "MH", "phoneCode": "+692"},
    {"label": "Mauritania", "value": "mauritania", "code": "MR", "phoneCode": "+222"},
    {"label": "Mauritius", "value": "mauritius", "code": "MU", "phoneCode": "+230"},
    {"label": "Mexico", "value": "mexico", "code": "MX", "phoneCode": "+52"},
    {"label": "Micronesia", "value": "micronesia", "code": "FM", "phoneCode": "+691"},
    {"label": "Moldova", "value": "moldova", "code": "MD", "phoneCode": "+373"},
    {"label": "Monaco", "value": "monaco", "code": "MC", "phoneCode": "+377"},
    {"label": "Mongolia", "value": "mongolia", "code": "MN", "phoneCode": "+976"},
    {"label": "Montenegro", "value": "montenegro", "code": "ME", "phoneCode": "+382"},
    {"label": "Morocco", "value": "morocco", "code": "MA", "phoneCode": "+212"},
    {"label": "Mozambique", "value": "mozambique", "code": "MZ", "phoneCode": "+258"},
    {"label": "Myanmar", "value": "myanmar", "code": "MM", "phoneCode": "+95"},
    {"label": "Namibia", "value": "namibia", "code": "NA", "phoneCode": "+264"},
    {"label": "Nauru", "value": "nauru", "code": "NR", "phoneCode": "+674"},
    {"label": "Nepal", "value": "nepal", "code": "NP", "phoneCode": "+977"},
    {"label": "Netherlands", "value": "netherlands", "code": "NL", "phoneCode": "+31"},
    {"label": "New Zealand", "value": "new_zealand", "code": "NZ", "phoneCode": "+64"},
    {"label": "Nicaragua", "value": "nicaragua", "code": "NI", "phoneCode": "+505"},
    {"label": "Niger", "value": "niger", "code": "NE", "phoneCode": "+227"},
    {"label": "Nigeria", "value": "nigeria", "code": "NG", "phoneCode": "+234"},
    {"label": "North Korea", "value": "north_korea", "code": "KP", "phoneCode": "+850"},
    {"label": "Norway", "value": "norway", "code": "NO", "phoneCode": "+47"},
    {"label": "Oman", "value": "oman", "code": "OM", "phoneCode": "+968"},
    {"label": "Pakistan", "value": "pakistan", "code": "PK", "phoneCode": "+92"},
    {"label": "Palau", "value": "palau", "code": "PW", "phoneCode": "+680"},
    {"label": "Palestine", "value": "palestine", "code": "PS", "phoneCode": "+970"},
    {"label": "Panama", "value": "panama", "code": "PA", "phoneCode": "+507"},
    {"label": "Papua New Guinea", "value": "papua_new_guinea", "code": "PG", "phoneCode": "+675"},
    {"label": "Paraguay", "value": "paraguay", "code": "PY", "phoneCode": "+595"},
    {"label": "Peru", "value": "peru", "code": "PE", "phoneCode": "+51"},
    {"label": "Philippines", "value": "philippines", "code": "PH", "phoneCode": "+63"},
    {"label": "Poland", "value": "poland", "code": "PL", "phoneCode": "+48"},
    {"label": "Portugal", "value": "portugal", "code": "PT", "phoneCode": "+351"},
    {"label": "Puerto Rico", "value": "puerto_rico", "code": "PR", "phoneCode": "+1"},
    {"label": "Qatar", "value": "qatar", "code": "QA", "phoneCode": "+974"},
    {"label": "Romania", "value": "romania", "code": "RO", "phoneCode": "+40"},
    {"label": "Russia", "value": "russia", "code": "RU", "phoneCode": "+7"},
    {"label": "Rwanda", "value": "rwanda", "code": "RW", "phoneCode": "+250"},
    {"label": "Saint Kitts and Nevis", "value": "saint_kitts_and_nevis", "code": "KN", "phoneCode": "+1"},
    {"label": "Saint Lucia", "value": "saint_lucia", "code": "LC", "phoneCode": "+1"},
    {"label": "Saint Vincent and the Grenadines", "value": "saint_vincent_and_the_grenadines", "code": "VC", "phoneCode": "+1"},
    {"label": "Samoa", "value": "samoa", "code": "WS", "phoneCode": "+685"},
    {"label": "San Marino", "value": "san_marino", "code": "SM", "phoneCode": "+378"},
    {"label": "Sao Tome and Principe", "value": "sao_tome_and_principe", "code": "ST", "phoneCode": "+239"},
    {"label": "Saudi Arabia", "value": "saudi_arabia", "code": "SA", "phoneCode": "+966"},
    {"label": "Senegal", "value": "senegal", "code": "SN", "phoneCode": "+221"},
    {"label": "Serbia", "value": "serbia", "code": "RS", "phoneCode": "+381"},
    {"label": "Seychelles", "value": "seychelles", "code": "SC", "phoneCode": "+248"},
    {"label": "Sierra Leone", "value": "sierra_leone", "code": "SL", "phoneCode": "+232"},
    {"label": "Singapore", "value": "singapore", "code": "SG", "phoneCode": "+65"},
    {"label": "Slovakia", "value": "slovakia", "code": "SK", "phoneCode": "+421"},
    {"label": "Slovenia", "value": "slovenia", "code": "SI", "phoneCode": "+386"},
    {"label": "Solomon Islands", "value": "solomon_islands", "code": "SB", "phoneCode": "+677"},
    {"label": "Somalia", "value": "somalia", "code": "SO", "phoneCode": "+252"},
    {"label": "South Africa", "value": "south_africa", "code": "ZA", "phoneCode": "+27"},
    {"label": "South Korea", "value": "south_korea", "code": "KR", "phoneCode": "+82"},
    {"label": "South Sudan", "value": "south_sudan", "code": "SS", "phoneCode": "+211"},
    {"label": "Spain", "value": "spain", "code": "ES", "phoneCode": "+34"},
    {"label": "Sri Lanka", "value": "sri_lanka", "code": "LK", "phoneCode": "+94"},
    {"label": "Sudan", "value": "sudan", "code": "SD", "phoneCode": "+249"},
    {"label": "Suriname", "value": "suriname", "code": "SR", "phoneCode": "+597"},
    {"label": "Swaziland", "value": "swaziland", "code": "SZ", "phoneCode": "+268"},
    {"label": "Sweden", "value": "sweden", "code": "SE", "phoneCode": "+46"},
    {"label": "Switzerland", "value": "switzerland", "code": "CH", "phoneCode": "+41"},
    {"label": "Syria", "value": "syria", "code": "SY", "phoneCode": "+963"},
    {"label": "Taiwan", "value": "taiwan", "code": "TW", "phoneCode": "+886"},
    {"label": "Tajikistan", "value": "tajikistan", "code": "TJ", "phoneCode": "+992"},
    {"label": "Tanzania", "value": "tanzania", "code": "TZ", "phoneCode": "+255"},
    {"label": "Thailand", "value": "thailand", "code": "TH", "phoneCode": "+66"},
    {"label": "Timor-Leste", "value": "timor_leste", "code": "TL", "phoneCode": "+670"},
    {"label": "Togo", "value": "togo", "code": "TG", "phoneCode": "+228"},
    {"label": "Tonga", "value": "tonga", "code": "TO", "phoneCode": "+676"},
    {"label": "Trinidad and Tobago", "value": "trinidad_and_tobago", "code": "TT", "phoneCode": "+1"},
    {"label": "Tunisia", "value": "tunisia", "code": "TN", "phoneCode": "+216"},
    {"label": "Turkey", "value": "turkey", "code": "TR", "phoneCode": "+90"},
    {"label": "Turkmenistan", "value": "turkmenistan", "code": "TM", "phoneCode": "+993"},
    {"label": "Tuvalu", "value": "tuvalu", "code": "TV", "phoneCode": "+688"},
    {"label": "Uganda", "value": "uganda", "code": "UG", "phoneCode": "+256"},
    {"label": "Ukraine", "value": "ukraine", "code": "UA", "phoneCode": "+380"},
    {"label": "United Arab Emirates", "value": "united_arab_emirates", "code": "AE", "phoneCode": "+971"},
    {"label": "United Kingdom", "value": "united_kingdom", "code": "GB", "phoneCode": "+44"},
    {"label": "United States", "value": "united_states", "code": "US", "phoneCode": "+1"},
    {"label": "Uruguay", "value": "uruguay", "code": "UY", "phoneCode": "+598"},
    {"label": "Uzbekistan", "value": "uzbekistan", "code": "UZ", "phoneCode": "+998"},
    {"label": "Vanuatu", "value": "vanuatu", "code": "VU", "phoneCode": "+678"},
    {"label": "Vatican City", "value": "vatican_city", "code": "VA", "phoneCode": "+379"},
    {"label": "Venezuela", "value": "venezuela", "code": "VE", "phoneCode": "+58"},
    {"label": "Vietnam", "value": "vietnam", "code": "VN", "phoneCode": "+84"},
    {"label": "Yemen", "value": "yemen", "code": "YE", "phoneCode": "+967"},
    {"label": "Zambia", "value": "zambia", "code": "ZM", "phoneCode": "+260"},
    {"label": "Zimbabwe", "value": "zimbabwe", "code": "ZW", "phoneCode": "+263"}
];